#include "GB/memory/cartridge_info.h"

CartridgeInfo::CartridgeInfo() {
    this->publisherNames.push_back("None");
    this->publisherNames.push_back("Nintendo Research & Development 1");
    this->publisherNames.push_back("Capcom");
    this->publisherNames.push_back("EA (Electronic Arts)");
    this->publisherNames.push_back("Hudson Soft");
    this->publisherNames.push_back("B-AI");
    this->publisherNames.push_back("KSS");
    this->publisherNames.push_back("Planning Office WADA");
    this->publisherNames.push_back("PCM Complete");
    this->publisherNames.push_back("San-X");
    this->publisherNames.push_back("Kemco");
    this->publisherNames.push_back("SETA Corporation");
    this->publisherNames.push_back("Viacom");
    this->publisherNames.push_back("Nintendo");
    this->publisherNames.push_back("Bandai");
    this->publisherNames.push_back("Ocean Software/Acclaim Entertainment");
    this->publisherNames.push_back("Konami");
    this->publisherNames.push_back("HectorSoft");
    this->publisherNames.push_back("Taito");
    this->publisherNames.push_back("Hudson Soft");
    this->publisherNames.push_back("Banpresto");
    this->publisherNames.push_back("Ubi Soft");
    this->publisherNames.push_back("Atlus");
    this->publisherNames.push_back("Malibu Interactive");
    this->publisherNames.push_back("Angel");
    this->publisherNames.push_back("Bullet-Proof Software");
    this->publisherNames.push_back("Irem");
    this->publisherNames.push_back("Absolute");
    this->publisherNames.push_back("Acclaim Entertainment");
    this->publisherNames.push_back("Activision");
    this->publisherNames.push_back("Sammy USA Corporation");
    this->publisherNames.push_back("Konami");
    this->publisherNames.push_back("Hi Tech Expressions");
    this->publisherNames.push_back("LJN");
    this->publisherNames.push_back("Matchbox");
    this->publisherNames.push_back("Mattel");
    this->publisherNames.push_back("Milton Bradley Company");
    this->publisherNames.push_back("Titus Interactive");
    this->publisherNames.push_back("Virgin Games Ltd.");
    this->publisherNames.push_back("Lucasfilm Games");
    this->publisherNames.push_back("Ocean Software");
    this->publisherNames.push_back("Infogrames");
    this->publisherNames.push_back("Interplay Entertainment");
    this->publisherNames.push_back("Broderbund");
    this->publisherNames.push_back("Sculptured Software");
    this->publisherNames.push_back("The Sales Curve Limited");
    this->publisherNames.push_back("THQ");
    this->publisherNames.push_back("Accolade");
    this->publisherNames.push_back("Misawa Entertainment");
    this->publisherNames.push_back("lozc");
    this->publisherNames.push_back("Tokuma Shoten");
    this->publisherNames.push_back("Tsukuda Original");
    this->publisherNames.push_back("Chunsoft Co.");
    this->publisherNames.push_back("Video System");
    this->publisherNames.push_back("Ocean Software/Acclaim Entertainment");
    this->publisherNames.push_back("Varie");
    this->publisherNames.push_back("Yonezawa/s’pal");
    this->publisherNames.push_back("Kaneko");
    this->publisherNames.push_back("Pack-In-Video");
    this->publisherNames.push_back("Bottom Up");
    this->publisherNames.push_back("Konami (Yu-Gi-Oh!)");
    this->publisherNames.push_back("MTO");
    this->publisherNames.push_back("Kodansha");
    this->publisherNames.push_back("Unknown");

    this->ramSizeNames.push_back("0");
    this->ramSizeNames.push_back("-");
    this->ramSizeNames.push_back("8 KiB");
    this->ramSizeNames.push_back("32 KiB");
    this->ramSizeNames.push_back("128 KiB");
    this->ramSizeNames.push_back("64 KiB");

    this->cartridgeTypes[0x00] = "ROM ONLY";
    this->cartridgeTypes[0x01] = "MBC1";
    this->cartridgeTypes[0x02] = "MBC1+RAM";
    this->cartridgeTypes[0x03] = "MBC1+RAM+BATTERY";
    this->cartridgeTypes[0x05] = "MBC2";
    this->cartridgeTypes[0x06] = "MBC2+BATTERY";
    this->cartridgeTypes[0x08] = "ROM+RAM 9";
    this->cartridgeTypes[0x09] = "ROM+RAM+BATTERY 9";
    this->cartridgeTypes[0x0B] = "MMM01";
    this->cartridgeTypes[0x0C] = "MMM01+RAM";
    this->cartridgeTypes[0x0D] = "MMM01+RAM+BATTERY";
    this->cartridgeTypes[0x0F] = "MBC3+TIMER+BATTERY";
    this->cartridgeTypes[0x10] = "MBC3+TIMER+RAM+BATTERY 10";
    this->cartridgeTypes[0x11] = "MBC3";
    this->cartridgeTypes[0x12] = "MBC3+RAM 10";
    this->cartridgeTypes[0x13] = "MBC3+RAM+BATTERY 10";
    this->cartridgeTypes[0x19] = "MBC5";
    this->cartridgeTypes[0x1A] = "MBC5+RAM";
    this->cartridgeTypes[0x1B] = "MBC5+RAM+BATTERY";
    this->cartridgeTypes[0x1C] = "MBC5+RUMBLE";
    this->cartridgeTypes[0x1D] = "MBC5+RUMBLE+RAM";
    this->cartridgeTypes[0x1E] = "MBC5+RUMBLE+RAM+BATTERY";
    this->cartridgeTypes[0x20] = "MBC6";
    this->cartridgeTypes[0x22] = "MBC7+SENSOR+RUMBLE+RAM+BATTERY";
    this->cartridgeTypes[0xFC] = "POCKET CAMERA";
    this->cartridgeTypes[0xFD] = "BANDAI TAMA5";
    this->cartridgeTypes[0xFE] = "HuC3";
    this->cartridgeTypes[0xFF] = "HuC1+RAM+BATTERY";


    RomSizeInfo info;
    info.name = "32 KiB";
    info.banks = 2;
    info.size = 32768;
    this->ROMSizes[0x00] = info;
    info.name = "64 KiB";
    info.banks = 4;
    info.size = 65536;
    this->ROMSizes[0x01] = info;
    info.name = "128 KiB";
    info.banks = 8;
    info.size = 131072;
    this->ROMSizes[0x02] = info;
    info.name = "256 KiB";
    info.banks = 16;
    info.size = 262144;
    this->ROMSizes[0x03] = info;
    info.name = "512 KiB";
    info.banks = 32;
    info.size = 524288;
    this->ROMSizes[0x04] = info;
    info.name = "1 MiB";
    info.banks = 64;
    info.size = 1048576;
    this->ROMSizes[0x05] = info;
    info.name = "2 MiB";
    info.banks = 128;
    info.size = 2097152;
    this->ROMSizes[0x06] = info;
    info.name = "4 MiB";
    info.banks = 256;
    info.size = 4194304;
    this->ROMSizes[0x07] = info;
    info.name = "8 MiB";
    info.banks = 512;
    info.size = 8388608;
    this->ROMSizes[0x08] = info;
    info.name = "1.1 MiB";
    info.banks = 72;
    info.size = 1153434;
    this->ROMSizes[0x52] = info;
    info.name = "1.2 MiB";
    info.banks = 80;
    info.size = 1258292;
    this->ROMSizes[0x53] = info;
    info.name = "1.5 MiB";
    info.banks = 96;
    info.size = 1572864;
    this->ROMSizes[0x54] = info;

    this->oldLicenseeCodes[0x00] = "None";
    this->oldLicenseeCodes[0x01] = "Nintendo";
    this->oldLicenseeCodes[0x08] = "Capcom";
    this->oldLicenseeCodes[0x09] = "HOT-B";
    this->oldLicenseeCodes[0x0A] = "Jaleco";
    this->oldLicenseeCodes[0x0B] = "Coconuts Japan";
    this->oldLicenseeCodes[0x0C] = "Elite Systems";
    this->oldLicenseeCodes[0x13] = "EA (Electronic Arts)";
    this->oldLicenseeCodes[0x18] = "Hudson Soft";
    this->oldLicenseeCodes[0x19] = "ITC Entertainment";
    this->oldLicenseeCodes[0x1A] = "Yanoman";
    this->oldLicenseeCodes[0x1D] = "Japan Clary";
    this->oldLicenseeCodes[0x1F] = "Virgin Games Ltd.3";
    this->oldLicenseeCodes[0x24] = "PCM Complete";
    this->oldLicenseeCodes[0x25] = "San-X";
    this->oldLicenseeCodes[0x28] = "Kemco";
    this->oldLicenseeCodes[0x29] = "SETA Corporation";
    this->oldLicenseeCodes[0x30] = "Infogrames5";
    this->oldLicenseeCodes[0x31] = "Nintendo";
    this->oldLicenseeCodes[0x32] = "Bandai";
    this->oldLicenseeCodes[0x33] = "Indicates that the New licensee code should be used instead.";
    this->oldLicenseeCodes[0x34] = "Konami";
    this->oldLicenseeCodes[0x35] = "HectorSoft";
    this->oldLicenseeCodes[0x38] = "Capcom";
    this->oldLicenseeCodes[0x39] = "Banpresto";
    this->oldLicenseeCodes[0x3C] = ".Entertainment i";
    this->oldLicenseeCodes[0x3E] = "Gremlin";
    this->oldLicenseeCodes[0x41] = "Ubi Soft1";
    this->oldLicenseeCodes[0x42] = "Atlus";
    this->oldLicenseeCodes[0x44] = "Malibu Interactive";
    this->oldLicenseeCodes[0x46] = "Angel";
    this->oldLicenseeCodes[0x47] = "Spectrum Holoby";
    this->oldLicenseeCodes[0x49] = "Irem";
    this->oldLicenseeCodes[0x4A] = "Virgin Games Ltd.3";
    this->oldLicenseeCodes[0x4D] = "Malibu Interactive";
    this->oldLicenseeCodes[0x4F] = "U.S. Gold";
    this->oldLicenseeCodes[0x50] = "Absolute";
    this->oldLicenseeCodes[0x51] = "Acclaim Entertainment";
    this->oldLicenseeCodes[0x52] = "Activision";
    this->oldLicenseeCodes[0x53] = "Sammy USA Corporation";
    this->oldLicenseeCodes[0x54] = "GameTek";
    this->oldLicenseeCodes[0x55] = "Park Place";
    this->oldLicenseeCodes[0x56] = "LJN";
    this->oldLicenseeCodes[0x57] = "Matchbox";
    this->oldLicenseeCodes[0x59] = "Milton Bradley Company";
    this->oldLicenseeCodes[0x5A] = "Mindscape";
    this->oldLicenseeCodes[0x5B] = "Romstar";
    this->oldLicenseeCodes[0x5C] = "Naxat Soft13";
    this->oldLicenseeCodes[0x5D] = "Tradewest";
    this->oldLicenseeCodes[0x60] = "Titus Interactive";
    this->oldLicenseeCodes[0x61] = "Virgin Games Ltd.3";
    this->oldLicenseeCodes[0x67] = "Ocean Software";
    this->oldLicenseeCodes[0x69] = "EA (Electronic Arts)";
    this->oldLicenseeCodes[0x6E] = "Elite Systems";
    this->oldLicenseeCodes[0x6F] = "Electro Brain";
    this->oldLicenseeCodes[0x70] = "Infogrames5";
    this->oldLicenseeCodes[0x71] = "Interplay Entertainment";
    this->oldLicenseeCodes[0x72] = "Broderbund";
    this->oldLicenseeCodes[0x73] = "Sculptured Software6";
    this->oldLicenseeCodes[0x75] = "The Sales Curve Limited7";
    this->oldLicenseeCodes[0x78] = "THQ";
    this->oldLicenseeCodes[0x79] = "Accolade";
    this->oldLicenseeCodes[0x7A] = "Triffix Entertainment";
    this->oldLicenseeCodes[0x7C] = "Microprose";
    this->oldLicenseeCodes[0x7F] = "Kemco";
    this->oldLicenseeCodes[0x80] = "Misawa Entertainment";
    this->oldLicenseeCodes[0x83] = "Lozc";
    this->oldLicenseeCodes[0x86] = "Tokuma Shoten";
    this->oldLicenseeCodes[0x8B] = "Bullet-Proof Software2";
    this->oldLicenseeCodes[0x8C] = "Vic Tokai";
    this->oldLicenseeCodes[0x8E] = "Ape";
    this->oldLicenseeCodes[0x8F] = "I’Max";
    this->oldLicenseeCodes[0x91] = "Chunsoft Co.8";
    this->oldLicenseeCodes[0x92] = "Video System";
    this->oldLicenseeCodes[0x93] = "Tsubaraya Productions";
    this->oldLicenseeCodes[0x95] = "Varie";
    this->oldLicenseeCodes[0x96] = "Yonezawa/S’Pal";
    this->oldLicenseeCodes[0x97] = "Kemco";
    this->oldLicenseeCodes[0x99] = "Arc";
    this->oldLicenseeCodes[0x9A] = "Nihon Bussan";
    this->oldLicenseeCodes[0x9B] = "Tecmo";
    this->oldLicenseeCodes[0x9C] = "Imagineer";
    this->oldLicenseeCodes[0x9D] = "Banpresto";
    this->oldLicenseeCodes[0x9F] = "Nova";
    this->oldLicenseeCodes[0xA1] = "Hori Electric";
    this->oldLicenseeCodes[0xA2] = "Bandai";
    this->oldLicenseeCodes[0xA4] = "Konami";
    this->oldLicenseeCodes[0xA6] = "Kawada";
    this->oldLicenseeCodes[0xA7] = "Takara";
}


void CartridgeInfo::setCartridgeInfo(const char* buffer, u32 size) {
    this->cartInfo.entrypoint = charsToU32(buffer, size, 0x100);
    this->cartInfo.nLogo = charsToString(buffer, size, 0x104, 0x2F);
    this->cartInfo.title = charsToString(buffer, size, 0x134, 0xF);
    this->cartInfo.mCode = charsToString(buffer, size, 0x13F, 0x4);
    this->cartInfo.gbcFlag = buffer[0x143];
    this->cartInfo.licenseCode = charsToString(buffer, size, 0x144, 0x2);
    this->cartInfo.sgbFlag = buffer[0x146];
    this->cartInfo.type = buffer[0x147];
    this->cartInfo.romSize = buffer[0x148];
    this->cartInfo.ramSize = buffer[0x149];
    this->cartInfo.destinationCode = buffer[0x14A];
    this->cartInfo.oldLicenseCode = buffer[0x14B];
    this->cartInfo.romVersion = buffer[0x14C];
    this->cartInfo.checksum = buffer[0x14D];
    this->cartInfo.gChecksum = charsToU16(buffer, size, 0x14E);
}

// I HATE THIS
PublisherKey CartridgeInfo::getPublisherKey(const char* key) {
    if (std::strcmp(key, "") == 0) return None;
    if (std::strcmp(key, "01") == 0) return NintendoRD1;
    if (std::strcmp(key, "08") == 0) return Capcom;
    if (std::strcmp(key, "13") == 0) return EA;
    if (std::strcmp(key, "18") == 0) return HudsonSoft1;
    if (std::strcmp(key, "19") == 0) return B_AI;
    if (std::strcmp(key, "20") == 0) return KSS;
    if (std::strcmp(key, "22") == 0) return PlanningOfficeWADA;
    if (std::strcmp(key, "24") == 0) return PCMComplete;
    if (std::strcmp(key, "25") == 0) return San_X;
    if (std::strcmp(key, "28") == 0) return Kemco;
    if (std::strcmp(key, "29") == 0) return SETACorporation;
    if (std::strcmp(key, "30") == 0) return Viacom;
    if (std::strcmp(key, "31") == 0) return Nintendo;
    if (std::strcmp(key, "32") == 0) return Bandai;
    if (std::strcmp(key, "33") == 0) return OceanAcclaim;
    if (std::strcmp(key, "34") == 0) return Konami1;
    if (std::strcmp(key, "35") == 0) return HectorSoft;
    if (std::strcmp(key, "37") == 0) return Taito;
    if (std::strcmp(key, "38") == 0) return HudsonSoft2;
    if (std::strcmp(key, "39") == 0) return Banpresto;
    if (std::strcmp(key, "41") == 0) return UbiSoft1;
    if (std::strcmp(key, "42") == 0) return Atlus;
    if (std::strcmp(key, "44") == 0) return MalibuInteractive;
    if (std::strcmp(key, "46") == 0) return Angel;
    if (std::strcmp(key, "47") == 0) return BulletProofSoftware;
    if (std::strcmp(key, "49") == 0) return Irem;
    if (std::strcmp(key, "50") == 0) return Absolute;
    if (std::strcmp(key, "51") == 0) return AcclaimEntertainment;
    if (std::strcmp(key, "52") == 0) return Activision;
    if (std::strcmp(key, "53") == 0) return SammyUSA;
    if (std::strcmp(key, "54") == 0) return Konami2;
    if (std::strcmp(key, "55") == 0) return HiTechExpressions;
    if (std::strcmp(key, "56") == 0) return LJN;
    if (std::strcmp(key, "57") == 0) return Matchbox;
    if (std::strcmp(key, "58") == 0) return Mattel;
    if (std::strcmp(key, "59") == 0) return MiltonBradleyCompany;
    if (std::strcmp(key, "60") == 0) return TitusInteractive;
    if (std::strcmp(key, "61") == 0) return VirginGames;
    if (std::strcmp(key, "64") == 0) return LucasfilmGames;
    if (std::strcmp(key, "67") == 0) return OceanSoftware;
    if (std::strcmp(key, "69") == 0) return EA;
    if (std::strcmp(key, "70") == 0) return Infogrames;
    if (std::strcmp(key, "71") == 0) return InterplayEntertainment;
    if (std::strcmp(key, "72") == 0) return Broderbund;
    if (std::strcmp(key, "73") == 0) return SculpturedSoftware;
    if (std::strcmp(key, "75") == 0) return TheSalesCurve;
    if (std::strcmp(key, "78") == 0) return THQ;
    if (std::strcmp(key, "79") == 0) return Accolade;
    if (std::strcmp(key, "80") == 0) return MisawaEntertainment;
    if (std::strcmp(key, "83") == 0) return lozc;
    if (std::strcmp(key, "86") == 0) return TokumaShoten;
    if (std::strcmp(key, "87") == 0) return TsukudaOriginal;
    if (std::strcmp(key, "91") == 0) return Chunsoft;
    if (std::strcmp(key, "92") == 0) return VideoSystem;
    if (std::strcmp(key, "93") == 0) return OceanAcclaim2;
    if (std::strcmp(key, "95") == 0) return Varie;
    if (std::strcmp(key, "96") == 0) return YonezawaSpal;
    if (std::strcmp(key, "97") == 0) return Kaneko;
    if (std::strcmp(key, "99") == 0) return PackInVideo;
    if (std::strcmp(key, "9H") == 0) return BottomUp;
    if (std::strcmp(key, "A4") == 0) return KonamiYuGiOh;
    if (std::strcmp(key, "BL") == 0) return MTO;
    if (std::strcmp(key, "DK") == 0) return Kodansha;
    return UNKNOWN;
}

u32 CartridgeInfo::getROMSize() {
    return this->ROMSizes[this->cartInfo.romSize].size;
}

u16 CartridgeInfo::getROMBankCount() {
    return this->ROMSizes[this->cartInfo.romSize].banks;
}

void CartridgeInfo::printCartridgeData() {
    std::cout << "Title: " << this->cartInfo.title << std::endl;
    std::cout << "Manufacturer: " << this->cartInfo.mCode << std::endl;

    std::cout << "License code: " << this->publisherNames[this->getPublisherKey(this->cartInfo.licenseCode.c_str())] << std::endl;
    std::cout << "Cartridge type: " << this->cartridgeTypes[this->cartInfo.type] << std::endl;

    std::cout << "ROM size: " << this->ROMSizes[this->cartInfo.romSize].name << std::endl;
    std::cout << "RAM size: " << this->ramSizeNames[this->cartInfo.ramSize] << std::endl;

    std::cout << "Old licensee: " << this->oldLicenseeCodes[this->cartInfo.oldLicenseCode] << std::endl;
}