#include "GB/instructions.h"

// **********************************

// NOP
SM83_INSTRUCTION_IMPLEMENTATION(NOP,)

SM83_INSTRUCTION_STEPS_IMPLEMENTATION(
    NOP, 
    SM83_INSTRUCTION_DECLARATION(NOP)
);

// *****

// LD BC, n16
SM83_INSTRUCTION_IMPLEMENTATION(LDBC, 

)

SM83_INSTRUCTION_IMPLEMENTATION(LDBC_P2, 

)

SM83_INSTRUCTION_IMPLEMENTATION(LDBC_P3, 

)

SM83_INSTRUCTION_STEPS_IMPLEMENTATION(
    LDBC, 
    SM83_INSTRUCTION_DECLARATION(LDBC), 
    SM83_INSTRUCTION_DECLARATION(LDBC_P2),
    SM83_INSTRUCTION_DECLARATION(LDBC_P3)
);

// *****


// **********************************

const SM83Opcode opcodesTable8Bit[] = {
    SM83_INSTRUCTION_INFO(0x00, "NOP",          1, 1, SM83_INSTRUCTION_STEPS_DECLARATION(NOP)),
    SM83_INSTRUCTION_INFO(0x01, "LD BC, d16",   3, 3, SM83_INSTRUCTION_STEPS_DECLARATION(LDBC))
};